#端口
server:
  port: 9010
  servlet:
    context-path: /zh

#日志级别
logging:
  level:
    com.zh.auth.mapper: debug
    com.zh.core.mapper: debug
#文件上传配置
Spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 1024MB #设置总上传的数据大小，最大请求文件的大小
      max-file-size: 1024MB #设置单个文件最大长度
      file-size-threshold: 100MB #当文件达到多少时进行磁盘写入
  datasource:
    url: jdbc:mysql://localhost:3306/recipe
    username: root
    password: zwk5231956
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    doc-expansion: none
infrastructure:
  security:
    token-expiration-hours: 720